{
 "title": "Loan Approval Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Health",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"prediction-service\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"172.16.238.10:8000\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prediction-service\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Request per 5 minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total{handler!=\"/metrics\"}[5m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\", handler!=\"/metrics\"}[5m]) / ignoring(le) increase(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Total requests per 5 minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"prediction-service\", handler!=\"/metrics\"}[5m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90 (5min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{handler!=\"/metrics\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}